// try{console.log(a+b);}catch(err){
//     console.log(err);
//     console.log("Error occured");
// }
// console.log("This line will not execute");
// try{
//     throw new ReferenceError();
// }catch(err){
//     //console.log(err);
//     console.log("Error handling success");
// }

//We cannot handle SyntaxError using try catch.
// try{
//     var a = "hello; 
// }catch(err){
//     console.log(err);
//     console.log("Experiment");
// }
// console.log("I don't know");